@@grammar::AlTeX
@@comments :: /#([^\n]*?)$/
@@parseinfo :: True

start
    =
    |   expression
    |   block
    ;


expression
    =
    | left:expression op:'+' ~ right:term
    | left:expression op:'-' ~ right:term
    | term
    ;


term
    =
    | left:term op:'**' ~ right:factor
    | left:term op:'*' ~ right:factor
    | left:term op:'/' ~ right:factor
    | factor
    ;


factor
    =
    | '(' @:expression ~ ')'
    | symbol
    | number
    ;

block
    =
    block_def ~ block_content $
    ;

block_def
    =
    (* имя_блока (параметры_блока):ньюлайн *)
    name:symbol ~ '(' params ')' ~ ':' NEWLINE $
    ;

params
    =
    {expression}+
    ;

block_content
    =
    NEWLINE INDENT {expression}+
    ;

(* matrix_def
    =
    'matrix' ~ '(' ~ height:number ~ ';' ~ width:number ~ ')' ~ ':' ~ block_content $
    ; *)

symbol = /[A-z]+/;


number = /[+-]?[0-9]*(\.)?[0-9]*/;
