@@grammar::CALC
@@eol_comments :: /#([^\n]*?)$/

start
    =
    expression $
    ;

expression
    =
    | left:expression op:'+' ~ right:term
    | left:expression op:'-' ~ right:term
    | term
    ;

term
    =
    | left:term op:'**' ~ right:factor
    | left:term op:'*' ~ right:factor
    | left:term op:'/' ~ right:factor
    | math_factorial
    | math_sin
    | math_cos
    | root
    | factor
    ;


math_factorial
    =
    op:'!' ~ middle:factor
    ;

root
    =
    left:factor op:'root(' ~ right:factor ')'
    ;

math_sin
        =
        op:'sin(' ~ middle:factor ')'
        ;

math_cos
        =
        op:'cos(' ~ middle:factor ')'
        ;

factor
    =
    | '(' ~ @:expression ')'
    | number_float
    | number_int
    | math_pi
    | math_e
    ;

math_pi
    =
    op:'pi'
    ;

math_e
    =
    op:'e'
    ;

number_float
    =
    /\d+\.\d+/
    ;

number_int
    =
    /\d+/
    ;
