@@grammar::CALC
@@eol_comments :: /\/\/.+/

start
    =
    expression $
    ;
    


expression
    =
    | left:expression op:'+' ~ right:term
    | left:expression op:'-' ~ right:term
    | term
    ;

term
    =
    | left:term op:'**' ~ right:factor
    | left:term op:'*' ~ right:factor
    | left:term op:'/' ~ right:factor
    | variable_name:factor op:'=' ~ variable_value:factor
    | factor
    ;



factor
    =
    | '(' ~ @:expression ')'
    | element
    ;





element
    =
    | /\d+/
    | /[^1-9][A-z]+/
    | /[^1-9][A-z]+_\d+/
    | /./
    ;

